version: '2'

networks:
  default-network:
    driver: bridge

services:

  nginx:
    build:
      context: .
      dockerfile: deployment/local/docker/nginx/Dockerfile
    ports:
      - "${DOCKER_NGINX_PORT}:80"
    volumes:
      - ./:/var/www
    depends_on:
      - php-fpm
    networks:
      - default-network

  php-fpm:
    build:
      context: .
      dockerfile: deployment/local/docker/php-fpm/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - pgsql
    container_name: yii2_crud_example_backend_php_fpm
    networks:
      - default-network

  pgsql:
    image: postgres:11.3
    ports:
      - "${DOCKER_PGSQL_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./persistent_data/pgsql:/var/lib/postgresql/data
    networks:
      - default-network